/*
 * Copyright 2012 Sadig <http://www.sadig.com>. All rights reserved.
 */
package br.unisinos.lb2.cloudbox;

import javax.swing.JOptionPane;

/**
 * Classe que mostra interface de autenticação para o usuário. Ele deve informar um login e senha para confirmar a 
 * autenticação. Caso algum campo tenha sido deixado em branco, uma mensagem de erro é exibida ao usuário.
 * @author Leandro Tonietto <ltonietto@unisinos.br>
 */
public class LoginDialog extends javax.swing.JDialog {

	public static final boolean OK = true;
	public static final boolean CANCELAR = false;
	private boolean state = CANCELAR;

	/**
	 * Creates new form LoginDialog
	 */
	public LoginDialog(java.awt.Frame parent) {
		super(parent, true);
		initComponents();
		if(parent != null){
			setLocation(parent.getX()+parent.getWidth()/2-this.getWidth()/2, parent.getY()+parent.getHeight()/2-this.getHeight()/2);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
	 * content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jPanel1 = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      tfLogin = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      tfPassword = new javax.swing.JTextField();
      jPanel2 = new javax.swing.JPanel();
      btOk = new javax.swing.JButton();
      btCancel = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      jLabel1.setBackground(new java.awt.Color(200, 200, 200));
      jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/unisinos/lb2/cloudbox/login.png"))); // NOI18N
      jLabel1.setText("Autenticação de usuário");
      jLabel1.setOpaque(true);
      getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

      jLabel2.setText("Login:");

      jLabel3.setText("Senha:");

      btOk.setText("Ok");
      btOk.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btOkActionPerformed(evt);
         }
      });
      jPanel2.add(btOk);

      btCancel.setText("Cancelar");
      btCancel.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btCancelActionPerformed(evt);
         }
      });
      jPanel2.add(btCancel);

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(22, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                     .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(tfLogin)
                     .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addContainerGap())
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(tfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
		confirmLogin();
   }//GEN-LAST:event_btOkActionPerformed

   private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
		cancelLogin();
   }//GEN-LAST:event_btCancelActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btCancel;
   private javax.swing.JButton btOk;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JPanel jPanel2;
   private javax.swing.JTextField tfLogin;
   private javax.swing.JTextField tfPassword;
   // End of variables declaration//GEN-END:variables

	/**
	 * Obter o lgoin digitado pelo usuário
	 * @return 
	 */
	public String getLogin() {
		if (state) {
			return tfLogin.getText();
		} else {
			return null;
		}
	}

	/**
	 * Obter a senha digitada pelo usuário
	 * @return 
	 */
	public String getPassword() {
		if (state) {
			return tfPassword.getText();
		} else {
			return null;
		}
	}

	/**
	 * Verificar se foi pressionado "Ok" ou "Cancelar"
	 * @return <code>true</code> caso usuário tenha pressionado "Ok"
	 */
	public boolean ok() {
		return state;
	}

	private void confirmLogin() {
		if ("".equals(tfLogin.getText())) {
			JOptionPane.showMessageDialog(this, "Login é obrigatório", "Login inválido", JOptionPane.ERROR_MESSAGE);
			return;
		}
		if ("".equals(tfPassword.getText())) {
			JOptionPane.showMessageDialog(this, "Senha é obrigatória", "Login inválido", JOptionPane.ERROR_MESSAGE);
			return;
		}
		state = true;
		dispose();
	}

	private void cancelLogin() {
		state = false;
		dispose();
	}
}
